#SKG建库sql
CREATE TABLE IF NOT EXISTS `12306_13w`(
   `id12306` INT UNSIGNED AUTO_INCREMENT,
   `account` VARCHAR(40) NOT NULL,
   `pwd1` VARCHAR(40) NOT NULL,
	 `NAME` VARCHAR(40) NOT NULL,
	 `IdNum` VARCHAR(40) NOT NULL,
	 `pwd2` VARCHAR(40) NOT NULL,
	 `phone` VARCHAR(40) NOT NULL,
	 `mailAddr` VARCHAR(40) NOT NULL,
	 `notice` VARCHAR(100),
   `submission_date` DATE,
   PRIMARY KEY ( `id12306` )
)ENGINE=InnoDB DEFAULT CHARSET=utf8;